# Do not use this Dockerfile

FROM ubuntu:latest

RUN apt-get update
# Installing prerequites
RUN apt install -y gawk patch bzip2 tar make libgmp-dev libmpfr-dev libmpc-dev gettext wget \
    libelf-dev texinfo bison flex sed git build-essential diffutils curl libjpeg-dev \
    libpng-dev python3 pkg-config libisofs-dev meson ninja-build rake \
    python3-pip python3-setuptools \
    python3-wheel ninja-build

# Preparing kos directory
RUN mkdir -p /opt/toolchains/dc && \
    chmod -R 755 /opt/toolchains/dc && \
    chown -R $(id -u):$(id -g) /opt/toolchains/dc

# KallistiOs
# Making Sega Dreamcast toolchains
# You may adapt the KallistiOS repository URL if needed
ARG dc_chain=stable
ARG makejobs=2
RUN git clone https://github.com/KallistiOS/KallistiOS.git /opt/toolchains/dc/kos && \
    cd /opt/toolchains/dc/kos/utils/dc-chain && \
    pwd && \
    make toolchain_profile=$dc_chain makejobs=$makejobs use_custom_dependencies=1 && \
    make gdb && \
    make clean && \
    rm -rf /opt/toolchains/dc/kos